### ISSUE TITLE
Enemies straight up can't kill you while using this mod

### ISSUE THREAD

**Issue by Sluka32** [Taiga74164/Non-Lethal-Company-Mod#12]
While using this mod i've noticed that enemies can't kill you, and some even straight up ignore you while having this mod enabled, i do not have god mode on, some of them try to kill me but they just walk trough my body, i dont know if its a compatibility problem

**Comment by Taiga74164** [comment]
no issue on our end when god mode is off

**Comment by Sluka32** [comment]
I tried to disable every single mod and just keep non lethal company, but again, no enemy is able to kill me, not even one hit enemies like the bracken or the dogs, it's almost like once you enable dumb enemies/god mode, it doesn't actually disable internally and it messes up everything
