### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by Xrndf** [Taiga74164/Non-Lethal-Company-Mod#2]
how to use it?

**Comment by KingRainbow44** [comment]
install BepInEx in your Lethal Company game directory; put the DLL file found in the release in the newly generated plugins folder

**Comment by uncreativeCultist** [comment]
you also need to have `HideManagerGameObject` set to `true` in your BepInEx.cfg file, or the mod menu doesn't work.

**Comment by KingRainbow44** [comment]
stale

**Comment by Hlebuw3k** [comment]
Setting HideManagerGameObject to true unfortunately breaks a lot of other mods for whatever reason, so as of right now this mod is unusable for me.
