### ISSUE TITLE
how do u open the gui

### ISSUE THREAD

**Issue by TDRpasta** [Taiga74164/Non-Lethal-Company-Mod#3]
cant figure out how to open the gui :/

**Comment by TDRpasta** [comment]
after spending forever searching through the code i found that the keybind is insert but i cant get it to work

**Comment by KingRainbow44** [comment]
are you running it in BepInEx?

**Comment by uncreativeCultist** [comment]
@TDRpasta, make sure you have `HideManagerGameObject` set to `true` in your BepInEx.cfg file, or the mod meenu doesn't work.

**Comment by cosmicstoaster** [comment]
where did you fine insert keybind

**Comment by cosmicstoaster** [comment]
find*

**Comment by KingRainbow44** [comment]
stale
