### ISSUE TITLE
Need new version for v45

### ISSUE THREAD

**Issue by trageat1** [Taiga74164/Non-Lethal-Company-Mod#7]
This is a great mod. Thank you for your efforts.
It now needs to adapt to the new version.

**Comment by uncreativeCultist** [comment]
what do you mean? what's wrong about it in it's current state?

it runs fine on the current version of the game. (v45)

**Comment by trageat1** [comment]
My bad, it runs fine on v45.
But it seems there's a problem with the scraps list. It ignores some scraps, such as Gift, Comedy, Tragedy…(new items added on v45)Sometime it cant list all of the scraps, it ignores horns and toy robots etc.
That issue doesn't have much impact. You can try to perfect it if you are free or I can continue to use menu1.0.
